<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function depcalc_ui_form_system_performance_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['clear_cache']['clear_depcalc_cache'] = [
    '#type' => 'submit',
    '#value' => t('Clear depcalc cache'),
    '#name' => 'clear_depcalc_cache',
    '#submit' => ['submitDepcalcCacheClear'],
    '#suffix' => t('Hint: Clear all caches won\'t clear depcalc cache.')
  ];
}

/**
 * Clears the depcalc cache.
 */
function submitDepcalcCacheClear(array &$form, FormStateInterface $form_state) {
  /** @var \Drupal\depcalc\Cache\DepcalcCacheBackend $depcalc_cache */
  $depcalc_cache = \Drupal::service('cache.depcalc');
  $depcalc_cache->deleteAllPermanent();
  \Drupal::messenger()->addStatus(t('Cleared all depcalc cache.'));
}
